workflows:
  ios-workflow:
    name: InformAR iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - apple_auth # Aquí irán tus credenciales de Apple luego
      vars:
        XCODE_PROJECT: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
    scripts:
      - name: Set permissions
        script: |
          chmod +x gradlew
      - name: Build shared module
        script: |
          chmod +x gradlew
          ./gradlew :shared:assembleSharedXcframework
      - name: Build iOS app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO
    artifacts:
      - shared/build/XCFrameworks/release/*.xcframework
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
